name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-rainier-cloudkid-link:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-to-r2-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.RAINIER_CLOUDKID_R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.RAINIER_CLOUDKID_R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto

      - name: Sync changed files to R2
        run: |
          aws s3 sync ./src s3://${{ secrets.RAINIER_CLOUDKID_R2_BUCKET }} \
            --endpoint-url https://${{ secrets.RAINIER_CLOUDKID_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --delete
