name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-rainier-cloudkid-link:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-to-r2-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - name: Upload to Bucket
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.RAINIER_CLOUDKID_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.RAINIER_CLOUDKID_R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.RAINIER_CLOUDKID_R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.RAINIER_CLOUDKID_R2_BUCKET }}
          source-dir: ./src
          destination-dir: ./
          keep-file-fresh: true
